name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 500

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
