name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'SoundBox.zip'
        exclusions: '*.git* *.bat* *.yml* temp.lua /*node_modules/* .editorconfig'
